# Generated by Django 2.2 on 2020-02-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renwick_Designs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
