# Generated by Django 2.2 on 2020-02-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renwick_Designs_app', '0002_auto_20200225_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='design',
            name='consultation',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='context',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='design',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='design',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='design',
            name='guests',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='design',
            name='project',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='design',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
