# Generated by Django 2.2 on 2020-02-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renwick_Designs_app', '0004_auto_20200225_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='context',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='guests',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='project',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
