# Generated by Django 2.2 on 2020-02-26 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Renwick_Designs_app', '0005_auto_20200225_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Renwick_Designs_app.Location'),
        ),
        migrations.AlterField(
            model_name='design',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Renwick_Designs_app.User'),
        ),
    ]
