# Generated by Django 2.2 on 2020-02-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renwick_Designs_app', '0006_auto_20200225_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=3),
        ),
    ]
